default: &default
  app:
    addr: "0.0.0.0:3000"
  db:
    type: {{ ENV "DB_TYPE" "sqlite" }}
    dsn: {{ ENV "DB_DSN" "gohighlight.db" }}
  es:
    enable: false
    url: {{ ENV "ES_URL" "http://localhost:9200" }}
    prefix: ""

debug:
  <<: *default
  db:
    type: mysql
    dsn: "root:rootpassword@tcp(127.0.0.1:3306)/gohighlights?charset=utf8mb4&parseTime=True&loc=Local"
  es:
    enable: true
    url: http://localhost:9200
    prefix: ""

release:
  <<: *default

test:
  <<: *default
  db:
    type: mysql
    dsn: "root:rootpassword@tcp(127.0.0.1:3306)/gohighlights_test?charset=utf8mb4&parseTime=True&loc=Local"
  es:
    enable: true
    url: http://localhost:9200
    prefix: test_